s = set()

i = input("enter the number: ")
s.add(int(i))
i = input("enter the number: ")
s.add(int(i))
i = input("enter the number: ")
s.add(int(i))
i = input("enter the number: ")
s.add(int(i))
i = input("enter the number: ")
s.add(int(i))
i = input("enter the number: ")
s.add(int(i))

print(s)